### ISSUE TITLE
REALLY THANKYOU!!!

### ISSUE THREAD

**Issue by proall** [hyugogirubato/Kamyroll-Python#10]
Hey, first of all: REALLY THANKYOU!!!
Searched days for a Script like this!

here is a few suggestions:
1. Auto Downloader (When Episode up to AIR)
2. Simply downloading (Put URL (Not working rn..), and Put URL (of the series, and let you see all the available EPs))
3. US bypasser (If there is one (cuz ik that was one before))
4. Speed UP the procces (Sometimes slow (maybe can faster to 10x speed(cuz the fastest now is 7.5 or something)))
5. Encrypt the Email and Passowrd (That not needed (but great to keeping the acc safe.))

Really ty for that Script and your hard work, plz keep UPDATE!

**Comment by insidewhy** [comment]
1. Could you be a bit more specific?
2. That would be really cool.
3. It's not possible without using a VPN/proxy, and even then crunchyroll automatically block most. I know a few that do work but writing about them in public will only bring the attention to crunchyroll.
4. Not possible.
5. We can encrypt them a little but we still need to send the plain password to crunchyroll so we can't encrypt it to the point that it wouldn't be non-trivial for someone to decrypt. We can still make it a little harder though.

**Comment by proall** [comment]
1. Auto downloader i mean that when episode came out to the website it will auto download the episode.
2. Nice, i will wait for that.
3. ok
4. ok
5. It will be great.

**Comment by hyugogirubato** [comment]
Thank you very much for your feedback.

I will provide some clarification:
1. I don't quite understand what you mean because it's a script and we are software.
2. This is a doable feature, I will look to add it.
3. I leave a better option now, I have explained how to use with the script the hola-vpn proxy which is free, fast and compatible with crunchyroll thus allowing to connect where you want, especially that crunchyroll to change its method and therefore a simple bypass is no longer enough.
4. The download speed is already at the max unfortunately because the video is segmented.
5. Feasible but does not change much.
